import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { withSSRContext } from 'aws-amplify'
import { listPosts } from '../src/graphql/queries'
import { AmplifyS3Image } from '@aws-amplify/ui-react'

export async function getServerSideProps () {
  const SSR = withSSRContext()
  const { data } = await SSR.API.graphql({
    query: listPosts
  })

  return {
    props: {
      posts: data.listPosts.items
    }
  }
} 

export default function Home({ posts }) {
  console.log(posts)
  return (
    <div className={styles.container}>
      <Head>
        <title>B. Heidelberg</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Link href='/create-post'>Create new Post </Link>
      </div>
      <main className={styles.main}>
        <h1>Hi there</h1>
        <p>My name is Billie Heidelberg and I am a Full Stack Developer</p>
      </main>
      <div className='image-grid'>
        { posts.map( post => {
            return (
            <div key={post.id } className='image-square'>
              <h1>{post.name}</h1>
              <AmplifyS3Image imgKey={post.image.key} height='40px' />
            </div>
        )})}
      </div>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
